version: '3'
services:
  server:
    build: './server'
    command: sh -c "yarn && nodemon ./server.js"
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
volumes:
  server: ~
